name: Firefly III
version: 3.1.26
slug: firefly-iii
description: A free and open source personal finance manager
url: https://github.com/coostax/addon-firefly-iii
webui: '[PROTO:ssl]://[HOST]:[PORT:80]'
services:
- mysql:want
arch:
- armv7
- amd64
hassio_api: true
map:
- ssl
ports:
  80/tcp: 3473
ports_description:
  80/tcp: Web interface
options:
  ssl: false
  certfile: fullchain.pem
  keyfile: privkey.pem
schema:
  remote_mysql_host: str?
  remote_mysql_database: str?
  remote_mysql_username: str?
  remote_mysql_password: password?
  remote_mysql_port: int?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  certfile: str
  keyfile: str
  ssl: bool
  mapbox_api_key: str?
  app_url: str?
  trusted_proxy: str?
init: false
image: ghcr.io/coostax/ha-addons/firefly-iii/{arch}
